### ISSUE TITLE
Board Members

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/pssi.org.in#11]
PSSI has 5 board members as of 2014. 

- President
- Vice-President
- Secretary
- Treasurer
- Joint-Secretary

It should be possible to tag user to designation for a time period. Board Member should be able to handle `past` and `present` members. It should be possible to hold same position in the past and future (Make relationship to user is `OneToMany`).

**Comment by vnbang2003** [comment]
@kracekumar @iambibhas 
I don't see designation section in models. Should we add new designation models and creation relation with user.

**Comment by kracekumar** [comment]
@vnbang2003 Here you go: https://github.com/pythonindia/pssi.org.in/blob/develop/apps/board/models.py#L6

**Comment by vnbang2003** [comment]
lost track of thing now as i didn't see it in admin section.
Will add in admin section also.

**Comment by vnbang2003** [comment]
Will work at make abou to display dynamically PSSI members profile.

**Comment by vnbang2003** [comment]
Have Completed this . Will send pull request soon.

**Comment by vnbang2003** [comment]
Sent pull request to fix it. https://github.com/pythonindia/pssi.org.in/pull/71
