### ISSUE TITLE
Monitoring and Alerting !

### ISSUE THREAD

**Issue by konarkmodi** [pythonindia/pssi.org.in#47]
Need to setup monitoring and other alerts. 

* URL up / down.
* Alert on 5xx
* Latency
* Logon failures.
* Various services uptime.

I can work on them.

**Comment by vnbang2003** [comment]
@konarkmodi ,
    I think we have completed with alert setup right  ?  Do you mind to share details offline with me , krace and bibhas.

**Comment by konarkmodi** [comment]
Hi

Yes, currently we have the basic set up for website up and down. Which I
think is good enough.

I will share the details in separate email with you.

Regards
Konark

**Comment by vnbang2003** [comment]
@konarkmodi  Please share details . 
Am closing this tickets now.
