### ISSUE TITLE
Add membership procedure steps

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/pssi.org.in#57]
We need to add our membership approval steps in membership page.

**Comment by vnbang2003** [comment]
@kracekumar 
I have added steps . Let me know i missed any steps.

How do I become a member of the PSSI ?
Procedure

   Create your account on pssi.org.in and fill your profile
   Once profile details are entered, click on apply for membership button in profile page
   One of PSSI board member will validate your profile info and approve it
   Once membership is approved, make the payment by following step in membership page
   Once payment is received you will be added to pssi mailing list as member
Criteria
  You need to be an Indian citizen.
  Pay a membership fee of INR 600/- to register yourself as a member for 2 years.

**Comment by kracekumar** [comment]
On Fri, Jan 30, 2015 at 9:23 PM, Vijay <notifications@github.com> wrote:

> @kracekumar <https://github.com/kracekumar>
> I have added steps . Let me know i missed any steps.
>
> How do I become a member of the PSSI ?
> Procedure
>
> Create your account on pssi.org.in and fill your profile
> Once profile details are entered, click on apply for membership button in
> profile page
> One of PSSI board member will validate your profile info and approve it
> Once membership is approved, make the payment by following step in
> membership page
> Once payment is received you will be added to pssi mailing list as member
> Criteria
> You need to be an Indian citizen.
> Pay a membership fee of INR 600/- to register yourself as a member for 2
> years.
>
> Instamojo page is collecting 500 Rs
https://www.instamojo.com/pssi/pssi-membership/. Everything else looks fine.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/pssi.org.in/issues/57#issuecomment-72221949>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by vnbang2003** [comment]
https://github.com/pythonindia/pssi.org.in/pull/66
