### ISSUE TITLE
Form to nominate board members

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/pssi.org.in#6]
PSSI is volunteer driven organization. Board members will be changed and new members will be nominated. We need to have form to nominate the new members. Also it should be possible to turn off nomination form for admin.

**Comment by shankig** [comment]
Can I take this implementation.

**Comment by vnbang2003** [comment]
@shankig  Yes

**Comment by shankig** [comment]
@vnbang2003 , I will update the models structure here before I start implementations . One info I needed, any key constraints that I need to keep in mind before I design model.

**Comment by vnbang2003** [comment]
it would be better to design the form without model and store this information in csv/txt.
Its a replacement for Google forms we use now.

**Comment by shankig** [comment]
Ok, great. Which location you prefer to keep the csv file?

**Comment by vnbang2003** [comment]
It could be great to store in root directory and make it visible only to admin group members.

**Comment by shankig** [comment]
You mean the project root directory. 
But I will suggest, to have media folder to store the nominations csv files. Something like pssi.org.in/media/nominate/

I am planning additional features, will put the proposal here.

**Comment by vnbang2003** [comment]
Any folder which is not exposed to public is fine . 
I would still think pssi.org.in/form_responses/  folder is good.

**Comment by shankig** [comment]
Proposal for nomination implementation
=======================================

- Admin can activate nomination by setting start date and end date for nomination and give a name to the nomination(say nomination 2015).

- On doing the above, a url will be generated that can be share for nomination form. This link will be active for the selected date range.

- For each nomination period a new csv file will be generated.

- May be we can also provide a link on admin interface to download the csv.

Please share thoughts on it.

**Comment by sayanchowdhury** [comment]
@vnbang2003 we can store in the data in database and generate a csv when required?

**Comment by vnbang2003** [comment]
As we don't store the result for voting result. 
Lets not store them in DB. For other thing we already have DB design.

**Comment by shankig** [comment]
two Questions:
- Whether my proposal is Ok.
- Are we going with direct csv storage, no DB storage.

**Comment by kracekumar** [comment]
My 2p

Use db and don't store any info about voter.

**Comment by shankig** [comment]
Finally what is decided?

**Comment by vnbang2003** [comment]
I don't have any problem in using DB but it just we will keep stale data year after year.
For voting we need to generate unique link for each user and should be visible once members logins in. We just capture  vote not voter details and it just once time useable link .

Hope this is clear now.

**Comment by vnbang2003** [comment]
Have Completed this . Will send pull request soon.

**Comment by vnbang2003** [comment]
Sent pull request. Hence closing it https://github.com/pythonindia/pssi.org.in/pull/71
