### ISSUE TITLE
Page subtitle is wrong

### ISSUE THREAD

**Issue by nibrahim** [pythonindia/pssi.org.in#74]
https://pssi.org.in/by-laws/ page has the wrong sub title. It currently says `India's premier conference on Python programming language` which is the line for PyCon. It would be best to just leave it empty.

**Comment by kracekumar** [comment]
This is fixed. Here is the screenshoot
![screen shot 2015-04-07 at 11 14 32 pm](https://cloud.githubusercontent.com/assets/311929/7029536/f430bd1a-dd7b-11e4-9d2b-a4c59dc0af13.png)

Thanks.

**Comment by nibrahim** [comment]
Thanks! No need for the screenshot though. I can look at the page. :)

**Comment by kracekumar** [comment]
:-)
