### ISSUE TITLE
KG award form

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/pssi.org.in#8]
Every year KG Award is given at `PyCon India`. Nomination for the award opens few months before the event. Admin must be able to create KG Award form. Details of the form should be discussed. Important point is this happens again and again, form should have end date for accepting responses.

**Comment by vnbang2003** [comment]
@sayanchowdhury 
    Any update on this form please ?

**Comment by vnbang2003** [comment]
Will work on it as Sayan looks to be occupied.

**Comment by vnbang2003** [comment]
Have Completed this . Will send pull request soon.

**Comment by vnbang2003** [comment]
Sent pull request. Hence closing it. https://github.com/pythonindia/pssi.org.in/pull/71
