### ISSUE TITLE
Page to display people who were financial support to Aboard

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/pssi.org.in#91]
We need to add page where we can display people who all availed our grant request.
This will help in transparency from our side.

**Comment by kracekumar** [comment]
+1

On Fri, Sep 11, 2015 at 2:34 PM, Vijay <notifications@github.com> wrote:

> We need to add page where we can display people who all availed our grant
> request.
> This will help in transparency from our side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/pssi.org.in/issues/91>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by vnbang2003** [comment]
@kracekumar Can you help with this ? We need add 3 people we supported.

**Comment by vnbang2003** [comment]
Added more details We actually supported 4 speakers.

12-01-2016    NISCHAL HP
14-12-2015    BARGAVA RAMAN S-
18-11-2015    RAGHOTHAM S
05-11-2014    HARIS INRAHIM K V
